GalactikFouteBole/GalactikFouteBole/Controllers/TeamController.cs
using GalactikFouteBole.Helpers;
using GalactikFouteBole.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GalactikFouteBole.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        /// <summary>
        /// Retourne la liste des équipes de foot sur une seule page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            List<Team> teams = TeamHelper.GetTeamList();
            foreach(Team team in teams)
            {
                team.ImgTeam = Url.Content("~/Content/ImgTeam/" + team.TeamId + ".png");
            }
            return View(teams);
        }

        /// <summary>
        /// Retourne une équipe dans son détail (nouvelle vue)
        /// </summary>
        /// <param name="idTeam"></param>
        /// <returns></returns>
        public ActionResult TeamDetails(int idTeam)
        {
            Team detailedTeam = TeamHelper.GetTeamById(idTeam);
            detailedTeam.ImgTeam = Url.Content("~/Content/ImgTeam/" + detailedTeam.TeamId + ".png");
           
            return View(detailedTeam);
        }

        [HttpGet]
        public ActionResult GetCompetTeams(int idTeam)
        {
            //Récupérer la liste de toutes les compétitions, puis afficher un bouton par competition avec nom et ID
            List<Competition> CompetList = CompetHelper.GetCompetListForATeam(idTeam);
            ViewData["TeamId"] = idTeam;
            
            return PartialView("~/Views/Team/CompetParticipated.cshtml", CompetList);
        }

        /// <summary>
        /// Récupère le graph statistique d'une équipe pour la compétition réalisée.
        /// </summary>
        /// <param name="idTeam"></param>
        /// <param name="idCompet"></param>
        /// <returns></returns>
        public ActionResult GetTeamStatsOnCompet(int idTeam, int idCompet)
        {

            //Récupération des stats et affichage
            Stats statsToDisplay = TeamHelper.GetStatsOfTeamForACompet(idTeam, idCompet);
            Competition c = CompetHelper.getCompetById(idCompet);
            //ViewData["idCompet"] = c.Id;
            ViewData["idTeam"] = idTeam;
            ViewData["TirCadre"] = statsToDisplay.tirCadré.ToString(CultureInfo.CreateSpecificCulture("en-US"));
            ViewData["Possession"] = statsToDisplay.PossessionBalles.ToString(CultureInfo.CreateSpecificCulture("en-US"));
            ViewData["Passes"] = statsToDisplay.PassesSuccess.ToString(CultureInfo.CreateSpecificCulture("en-US"));
            ViewData["Dududu"] = statsToDisplay.DuelAerienWon.ToString(CultureInfo.CreateSpecificCulture("en-US"));
            ViewData["CartonJaune"] = statsToDisplay.CartonJaunes;
            ViewData["CartonRouge"] = statsToDisplay.CartonsRouges;
            return PartialView("~/Views/Team/Stats.cshtml", statsToDisplay);
        }

        public ActionResult EditTeamDetails(int idTeam)
        {
            Team team = TeamHelper.GetTeamById(idTeam);
            return View(team);
        }

        [HttpPost]
        public ActionResult EditingTeamDetails(int idTeam, string TeamName, string description)
        {
           bool isAdmin =  Globals.Variables.CurrentUser.IsAdmin;

            if(isAdmin)
            {
                Team team = TeamHelper.GetTeamById(idTeam);
                //Edition de l'équipe via son ID
                Team editedTeam = TeamHelper.EditTeamDetails(idTeam, TeamName, description);
                ViewData["teamName"] = team.TeamName;
                return View(editedTeam);
            }
            return null;
        }
    }
}

GalactikFouteBole/GalactikFouteBole/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GalactikFouteBole.Models;
using GalactikFouteBole.Globals;
using GalactikFouteBole.Helpers;

namespace GalactikFouteBole.Controllers
{
    public class UserProfileController : Controller
    {
        // GET: UserProfile
        public ActionResult Index()
        {
            User currentUser = Variables.CurrentUser;
            if (currentUser != null)
            {
                System.Diagnostics.Debug.WriteLine("Current user page profil: " + currentUser.Name);
                return View(BlogHelper.GetInvalidComments());
            }
            else
                return View("~/Views/Home/Connect.cshtml");
        }

        [HttpPost]
        public ActionResult UpdatedUserFields(User user)
        {
            UsersHelper.UpdateUserDetails(user);
            return View();
        }

        [HttpPost]
        public ActionResult ValidateComs(int[] comsToValidate)
        {
            BlogHelper.ValidateComments(comsToValidate);
            return View(BlogHelper.GetInvalidComments());
        }
    }
}

GalactikFouteBole/GalactikFouteBole/Views/Shared/_Layout.cshtml
@{ 
    GalactikFouteBole.Models.User currentUser = GalactikFouteBole.Globals.Variables.CurrentUser;
    String userName = "Aucun";
    if (currentUser != null)
    {
        userName = currentUser.UserName;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Galaktik Foute Bole</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GalakTikeFouteBole", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Profil utilisateur", "Index", "UserProfile")</li>
                    <li>@Html.ActionLink("Blogs", "Index", "Blogs")</li>
                    <li>@Html.ActionLink("Compéitions", "Index", "Compet")</li>
                    <li>@Html.ActionLink("Equipes", "Index","Team")</li>
                    <li>@Html.ActionLink("Connexion", "Connect", "Home")</li>
                    <li>@Html.ActionLink("Deconnexion", "Disconnect", "Home")</li>
                    <li style="color: red; font-weight: bold">Utilisateur connecté : @userName</li>
                </ul>
            
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - GalaktikFouteBole</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>